# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/con_cpu.xdc

# IP: ip/DS_DRAM/DS_DRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DS_DRAM || ORIG_REF_NAME==DS_DRAM} -quiet] -quiet

# IP: ip/CS_DRAM/CS_DRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CS_DRAM || ORIG_REF_NAME==CS_DRAM} -quiet] -quiet

# XDC: d:/Xilinx/Vivado/projects-ps/JMP_Predict_CPU/JMP_Predict_CPU.gen/sources_1/ip/DS_DRAM/DS_DRAM_ooc.xdc

# XDC: d:/Xilinx/Vivado/projects-ps/JMP_Predict_CPU/JMP_Predict_CPU.gen/sources_1/ip/CS_DRAM/CS_DRAM_ooc.xdc
